CREATE TABLE students
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name  VARCHAR(100) NOT NULL,
    birth_date DATE         NOT NULL,
    email      VARCHAR(255) NOT NULL,
    phone      VARCHAR(30)  NOT NULL,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_students_email UNIQUE (email)
);

CREATE TABLE courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    description TEXT,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_courses_name UNIQUE (name)
);

CREATE TABLE enrollments
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id          BIGINT      NOT NULL,
    course_id           BIGINT      NOT NULL,
    enrolled_at         TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completion_deadline DATE        NOT NULL,
    completed_at        TIMESTAMPTZ,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    CONSTRAINT fk_enrollments_student
        FOREIGN KEY (student_id) REFERENCES students (id),

    CONSTRAINT fk_enrollments_course
        FOREIGN KEY (course_id) REFERENCES courses (id),

    CONSTRAINT uk_enrollments_student_course
        UNIQUE (student_id, course_id),

    CONSTRAINT ck_enrollments_status
        CHECK (status IN ('ACTIVE', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX idx_enrollments_student_status
    ON enrollments (student_id, status);

CREATE TABLE task_logs
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enrollment_id BIGINT      NOT NULL,
    category      VARCHAR(30) NOT NULL,
    description   TEXT        NOT NULL,
    started_at    TIMESTAMPTZ NOT NULL,
    ended_at      TIMESTAMPTZ NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_task_logs_enrollment
        FOREIGN KEY (enrollment_id) REFERENCES enrollments (id),

    CONSTRAINT ck_task_logs_category
        CHECK (category IN (
                            'PESQUISA',
                            'PRATICA',
                            'ASSISTIR_VIDEOAULA'
            )),

    CONSTRAINT ck_task_logs_time
        CHECK (ended_at > started_at)
);

CREATE INDEX idx_task_logs_enrollment
    ON task_logs (enrollment_id);

CREATE INDEX idx_task_logs_started_at
    ON task_logs (started_at);